version: '3.9'

services:
  webapi:
    build:
      context: .
      dockerfile: ./ElectricityApi/Dockerfile
    hostname: localhost
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      ConnectionStrings__DefaultConnection: "Server=localhost;Database=Electricity;Trusted_Connection=True;"
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"

networks:
    default:
        driver: bridge
        ipam:
            config:
            - subnet: 172.16.57.0/24